version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven dependencies in offline mode"
      - mvn -B -q --update-snapshots dependency:go-offline

  build:
    commands:
      - echo "Running unit tests under the TEST profile (H2 in-memory)"
      - mvn -B test -Dspring.profiles.active=test

      - echo "Building production JAR (skip tests, use 'prod' profile)"
      - mvn -B package -DskipTests -Dspring.profiles.active=prod

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Uploading JAR to S3 artifact bucket"
      # Make sure ARTIFACTS_BUCKET is set in CodeBuild env vars (e.g. user-login-logs-bucket)
      - aws s3 cp target/user-management-cloud-0.0.1-SNAPSHOT.jar s3://$ARTIFACTS_BUCKET/$CODEBUILD_BUILD_NUMBER.jar

      - echo "Creating new Elastic Beanstalk application version"
      # Collapse into one line so $EB_APP and $CODEBUILD_BUILD_NUMBER get interpolated
      - aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label $CODEBUILD_BUILD_NUMBER --source-bundle S3Bucket=$ARTIFACTS_BUCKET,S3Key=$CODEBUILD_BUILD_NUMBER.jar

      - echo "Updating Elastic Beanstalk environment to new version"
      - aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - target/user-management-cloud-0.0.1-SNAPSHOT.jar
