# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      # Switch to Java 17, because our pom.xml / annotation processors /
      # Lombok versions are written for Java 17.
      java: corretto17
    commands:
      - echo "Installing Maven dependencies in offline mode"
      - mvn -B -q --update-snapshots dependency:go-offline

  build:
    commands:
      - echo "Running unit tests under the TEST profile (H2 in-memory)"
      - mvn -B test -Dspring.profiles.active=test

      - echo "Building production JAR (skip tests, use 'prod' profile)"
      - mvn -B package -DskipTests -Dspring.profiles.active=prod

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Uploading JAR to S3 artifact bucket"
      # ↪ Make sure ARTIFACTS_BUCKET is defined in your CodeBuild env vars
      - aws s3 cp target/user-management-cloud-0.0.1-SNAPSHOT.jar s3://$ARTIFACTS_BUCKET/$CODEBUILD_BUILD_NUMBER.jar

      - echo "Creating new Elastic Beanstalk application version"
      # ↪ Make sure EB_APP (your EB application name) is defined
      #    and EB_ENV (your EB environment name) is defined.
      - aws elasticbeanstalk create-application-version \
        --application-name $EB_APP \
        --version-label $CODEBUILD_BUILD_NUMBER \
        --source-bundle S3Bucket=$ARTIFACTS_BUCKET,S3Key=$CODEBUILD_BUILD_NUMBER.jar

      - echo "Updating Elastic Beanstalk environment to new version"
      - aws elasticbeanstalk update-environment \
        --environment-name $EB_ENV \
        --version-label $CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - target/user-management-cloud-0.0.1-SNAPSHOT.jar
