spring:
  profiles: prod

  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${SERVER_PORT:5000}

login:
  log:
    bucket: ${LOGIN_LOG_BUCKET}

cloudwatch:
  log-group-name: ${LOG_GROUP_NAME}