spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${SERVER_PORT:5000}

login:
  bucket: ${LOGIN_LOG_BUCKET}

cloudwatch:
  log-group-name: ${LOG_GROUP_NAME}
